device: "cuda"
dtype: "fp32"
learnable_add: false
load_ref_model: false
ref_model_dir: "model_repo/opt-125m"
ref_model_dtype: null
num_hidden_layers: 1
finetune_embedding: true
model_path: null
max_seq_len: 64
batch_size: 128
base_lr: 0.0000001
resume_train: true
dataloader_num_workers: 32
dataloader_prefetch_factor: 20
save_checkpoint_iters: 5000
max_iters: 2000000
warmup_iters: 5000
val_iters: 5000
cosineannealinglr_tmax: 20000
max_keep_ckpts: 2
